[tool.poetry]
name = "meetup-python-prom"
version = "0.1.0"
description = ""
authors = ["Chris <christopher.louet@pm.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
