---
global:
  scrape_interval: 10s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          environment: demo
#  - job_name: 'node'
#    static_configs:
#      - targets: ['node-exporter:9100']
  - job_name: 'node'
    file_sd_configs:
      - files:
          - /etc/prometheus/file_sd/node.yml

# alert
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - "alertmanager:9093"

rule_files:
  - 'alert.rules'
